server:
  port: 9001 # 服务端口
spring:
  application:
    name: nacos-register # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.11:8848,192.168.1.11:8850,192.168.1.11:8852 # nacos地址
        username: nacos # nacos用户名
        password: nacos # nacos密码